
CREATE DATABASE IF NOT EXISTS ERPBUSINESS;
USE ERPBUSINESS;

-- Crear tabla de Alumnos
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USR VARCHAR(100) PRIMARY KEY,  
    ROLEE VARCHAR(1),
    PASS VARCHAR(100),
    MATRICULA VARCHAR(100)

);

CREATE TABLE IF NOT EXISTS USUARIOS_DETAIL (
    ID_USR VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO_M VARCHAR(100),
    APELLIDO_P VARCHAR(100),
    FECHA_NAC DATE,
    EMAIL VARCHAR(100) UNIQUE,
    TELEFONO VARCHAR(10) UNIQUE
);

CREATE TABLE IF NOT EXISTS PRODUCTOS(
    ID_PROD VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(100),
    MARCA VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PRECIOS(
    ID_PROD VARCHAR(20) PRIMARY KEY,
    PRECIO INT
);

CREATE TABLE IF NOT EXISTS VENTAS(
    ID_PROD VARCHAR(20),
    FECHA DATE,
    PRECIO INT,
    CANTIDAD INT
);

CREATE TABLE IF NOT EXISTS CUENTAS_T(
    NOMBRE VARCHAR(100),
    NATURALEZA VARCHAR(100)
)


INSERT INTO USUARIOS(ID_USR,ROLEE,PASS,MATRICULA) VALUES("USUARIO123","1","TUTSIFRUTA123","USU123");
INSERT INTO USUARIOS(ID_USR,ROLEE,PASS,MATRICULA) VALUES("INVENTARIO123","2","PELOPONESO","INV123");
INSERT INTO USUARIOS(ID_USR,ROLEE,PASS,MATRICULA) VALUES("ADMINISTRATIVO123","3","SECRETARIA","ADMNST123");
INSERT INTO USUARIOS(ID_USR,ROLEE,PASS,MATRICULA) VALUES("ADMIN123","99","LINUX","ADMIN123");

INSERT INTO USUARIOS_DETAIL(ID_USR,NOMBRE,APELLIDO_M,APELLIDO_P,FECHA_NAC,EMAIL,TELEFONO) VALUES("USUARIO123","EL TIO","TITO","SUñIGA",'1990-12-12',"TIOTITO@GMAIL.COM",1234567890);

INSERT INTO PRODUCTOS(ID_PROD,NOMBRE,,MARCA) VALUES("COCA600","COCA COLA 600ML","COCA COLA");

INSERT INTO PRECIOS(ID_PROD,PRECIO) VALUES("COCA600",25);

INSERT INTO VENTAS(ID_PROD,FECHA,PRECIO,CANTIDAD) VALUES("COCA600",'1990-12-12',25,10);
