
CREATE DATABASE IF NOT EXISTS ERPBUSINESS;
USE ERPBUSINESS;

-- Crear tabla de Alumnos
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USR VARCHAR(100) PRIMARY KEY,  
    ROLE VARCHAR(1),
    PASS VARCHAR(100),
    MATRICULA VARCHAR(100)

);

CREATE TABLE IF NOT EXISTS USUARIOS_DETAIL (
    ID_USR VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO_M VARCHAR(100),
    APELLIDO_P VARCHAR(100),
    FECHA_NAC DATE,
    EMAIL VARCHAR(100) UNIQUE,
    TELEFONO VARCHAR(10) UNIQUE
);

CREATE TABLE IF NOT EXISTS PRODUCTOS(
    ID_PROD VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(100),
    MARCA VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PRECIOS(
    ID_PROD VARCHAR(20) PRIMARY KEY,
    PRECIO INT
);

CREATE TABLE IF NOT EXISTS VENTAS(
    ID_PROD VARCHAR(20),
    FECHA DATE,
    PRECIO INT,
    CANTIDAD INT
);

CREATE TABLE IF NOT EXISTS CUENTAS_T(
    NOMBRE VARCHAR(100),
    NATURALEZA VARCHAR(100)
)

INSERT INTO USUARIOS VALUES("USUARIO123","1","TUTSIFRUTA123","USU123");
INSERT INTO USUARIOS VALUES("INVENTARIO123","2","PELOPONESO","INV123");
INSERT INTO USUARIOS VALUES("ADMINISTRATIVO123","3","SECRETARIA","ADMNST123");
INSERT INTO USUARIOS VALUES("ADMIN123","99","LINUX","ADMIN123");

INSERT INTO USUARIOS_DETAIL VALUES("USUARIO123","EL TIO","TITO","SUñIGA",12-12-1990,"TIOTITO@GMAIL.COM",1234567890);


INSERT INTO PRODUCTOS VALUES("COCA600","COCA COLA 600ML","COCA COLA");

INSERT INTO PRECIOS VALUES("COCA600",25);

INSERT INTO VENTAS VALUES("COCA600",12-12-1990,25,10);
